export const SOCIALIZATION_CHECKLIST: { category: string; items: string[] }[] = [
  {
    category: "People",
    items: [
      "Children (toddlers)",
      "Children (older kids)",
      "Elderly person",
      "Person with hat/sunglasses",
      "Person with beard",
      "Person in uniform",
      "Person with umbrella",
      "Person in wheelchair",
      "Large group of people",
    ],
  },
  {
    category: "Animals",
    items: [
      "Friendly adult dog",
      "Friendly puppy",
      "Cat",
      "Small animals (rabbit, hamster)",
      "Birds",
      "Livestock (if applicable)",
    ],
  },
  {
    category: "Surfaces",
    items: [
      "Grass",
      "Concrete/pavement",
      "Gravel",
      "Sand",
      "Metal grate",
      "Wet surface",
      "Stairs",
      "Elevator",
    ],
  },
  {
    category: "Sounds",
    items: [
      "Thunder/fireworks",
      "Vacuum cleaner",
      "Doorbell",
      "Sirens",
      "Construction noise",
      "Music/TV",
      "Clapping/cheering",
      "Hair dryer",
    ],
  },
  {
    category: "Environments",
    items: [
      "Car ride",
      "Vet office (happy visit)",
      "Pet store",
      "Busy street",
      "Park",
      "Parking lot",
      "Different rooms in house",
      "Friend's house",
      "Outdoor cafe",
    ],
  },
  {
    category: "Handling",
    items: [
      "Paws touched",
      "Ears examined",
      "Mouth opened",
      "Nails trimmed",
      "Bathed",
      "Brushed/groomed",
      "Collar/harness put on",
      "Leash walking",
      "Picked up/held",
    ],
  },
  {
    category: "Objects",
    items: [
      "Skateboard/scooter",
      "Bicycle",
      "Stroller",
      "Shopping cart",
      "Balloons",
      "Plastic bags",
      "Broom/mop",
    ],
  },
];
