steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/wuf:$COMMIT_SHA"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/wuf:$COMMIT_SHA"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "wuf"
      - "--image"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/wuf:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--set-env-vars"
      - "FIREBASE_PROJECT_ID=$PROJECT_ID"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"
      - "--memory"
      - "512Mi"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "2"

options:
  logging: CLOUD_LOGGING_ONLY
