steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg"
      - "NEXT_PUBLIC_VAPID_PUBLIC_KEY=${_VAPID_PUBLIC_KEY}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_API_KEY=${_FIREBASE_API_KEY}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_PROJECT_ID=$PROJECT_ID"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/wuf:$COMMIT_SHA"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/wuf:$COMMIT_SHA"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "wuf"
      - "--image"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/wuf:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--set-env-vars"
      - "FIREBASE_PROJECT_ID=$PROJECT_ID,VAPID_PRIVATE_KEY=${_VAPID_PRIVATE_KEY},NEXT_PUBLIC_VAPID_PUBLIC_KEY=${_VAPID_PUBLIC_KEY},VAPID_SUBJECT=mailto:me@paulchun.com,STORAGE_BUCKET=wuf-medical-records,ANTHROPIC_API_KEY=${_ANTHROPIC_API_KEY},GEMINI_API_KEY=${_GEMINI_API_KEY},STRIPE_SECRET_KEY=${_STRIPE_SECRET_KEY},STRIPE_WEBHOOK_SECRET=${_STRIPE_WEBHOOK_SECRET},STRIPE_PRICE_ID=${_STRIPE_PRICE_ID}"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"
      - "--memory"
      - "512Mi"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "2"

substitutions:
  _VAPID_PUBLIC_KEY: "BBmQ7aCizBLttegsoqoiaeiIjz_2lx7I5nKoC6QBYYJhEyPBA__e3TumEFsL1yXHAVcs27-L-ZlB2NMlO2_Jp_4"
  _VAPID_PRIVATE_KEY: "DMJKPiEd0QhYZCgB69S91ps586Oj7Bdr5e4un6B0-ME"
  _FIREBASE_API_KEY: "AIzaSyC2u4nkuyMhLQpySHkKtOSdiAD6Hgy6HS8"
  _FIREBASE_AUTH_DOMAIN: "fattytoro.firebaseapp.com"
  _ALLOWED_EMAIL: "me@paulchun.com|nanshan7596@gmail.com"
  _ANTHROPIC_API_KEY: ""
  _GEMINI_API_KEY: ""
  _STRIPE_SECRET_KEY: ""
  _STRIPE_WEBHOOK_SECRET: ""
  _STRIPE_PRICE_ID: ""

options:
  logging: CLOUD_LOGGING_ONLY
